server:
  port: 8080

spring:
  name: docker
  application:
    name: CodeChallengeFlux
  datasource:
    url: jdbc:postgresql://postgres:5432/test_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  exposed:
    generate-ddl: true
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
---
spring:
  name: local
  application:
    name: CodeChallengeFlux
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  exposed:
    generate-ddl: true
  docker:
    compose:
      enabled: false
      file: docker-compose.yml